name: tag-to-docker
on:
  pull_request:
env:
  REGISTRY_HOST: "eu.gcr.io"
  REGISTRY_PATH: "ccc"
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: get info
        run: env | sort
